# Generated by Django 5.0.6 on 2024-07-07 21:02

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_address_order_city_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
