# Generated by Django 5.0.7 on 2024-07-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_state',
            field=models.BooleanField(default=False),
        ),
    ]
