# Generated by Django 5.0.7 on 2024-07-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_order_payment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
