# Generated by Django 5.0.6 on 2024-07-03 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Image', models.ImageField(upload_to='')),
                ('Type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Products.typeproduct')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
